CREATE SCHEMA [Cache]
GO
CREATE TABLE [Cache].[CacheItemMetaData](
	[InternalId] [bigint] IDENTITY(1,1) NOT NULL,
	[Key] [nvarchar](255) NOT NULL,
	[Created] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_CacheItemMetaData] PRIMARY KEY CLUSTERED 
(
	[InternalId] ASC,
	[Created] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [Cache].[CacheItem](
	[InternalId] [bigint] NOT NULL,
	[Content] [varbinary](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[InternalId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]